name: clang-format Check
on:
  push:
    branches: [ "SECRECY-DEV" ]
  pull_request:
    types:
      - opened
      - ready_for_review
      - synchronize
      - reopened
    branches:
      - SECRECY-DEV
jobs:
  formatting-check:
    if: github.event.pull_request.draft == false
    
    # to be safe. actually takes ~ 1 min
    timeout-minutes: 5
    
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run clang-format
      uses: jidicula/clang-format-action@v4.15.0
      with:
        clang-format-version: '20'